apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netflix-clone-k8s.fullname" . }}-secret
  labels:
    {{- include "netflix-clone-k8s.labels" . | nindent 4 }}
type: Opaque
data:
  # These values should be base64 encoded.
  username: {{ .Values.secret.username | b64enc }}
  password: {{ .Values.secret.password | b64enc }}
